---
title: "FINAL_ENHANCER_CHIP_SUMMARY"
author: "Alexander Glahs"
date: "16 Mai 2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries,  warning=FALSE, message=FALSE}

source("https://bioconductor.org/biocLite.R")
#biocLite("ggplot2")
#biocLite("heatmap.2")
#biocLite("heatmap")
#biocLite("fpc")
#biocLite("pvclust")
#biocLite("gplots")
#biocLite("rngtools")


library(ggplot2)
#library(heatmap)
#library(fpc)
library(pvclust)
#library(heatmap.2)
library(gplots)
#library(rngtools)
#library(NMF)



library(EDASeq)
library(fdrtool)
library(kableExtra)
library(knitr)
library(tidyr)
library(made4)
library(corrplot)
library(tidyverse)
library(purrr)
library(dplyr)
library(EDASeq)
library(fdrtool)
library(kableExtra)
library(knitr)
library(tidyr)
library(made4)
library(corrplot)
#library(reshape)
library(reshape2)

```

```{r LoadData,  warning=FALSE}

ID_table <-  read.table("C:/Users/Admin/Documents/Name_conversion_NM_FbGn_complete_unirot-gene_ID_master_list.csv",stringsAsFactors=F, sep= "\t",header=TRUE) 

data <- read.table("C:/Users/Admin/Documents/RNA_seq_Ali/File S1 - VST counts.csv",stringsAsFactors=F, sep= ",",header=TRUE) 
data_2 <- read.table("C:/Users/Admin/Documents/RNA_seq_Ali/File S1 - VST counts.csv",stringsAsFactors=F, sep= ",")

VST_counts <- data
colnames(VST_counts) <- data_2[1,]

#Load ChiP data

#ChIPdata

#With associated genes
data_ATAC <- read.table("C:/Users/Admin/Documents/MultiBamCov_ATAC_peaks_non_promoter_non_coding_exons_peaks_all_marks_dm6_complete_witch_losest_gene.bed" ,stringsAsFactors=F, sep='\t')
data_ATAC_all <- read.table("C:/Users/Admin/Documents/MultiBamCov_ATAC_peaks_non_promoter_peaks_all_marks_dm6_complete_with_closest_gene.bed" ,stringsAsFactors=F, sep='\t')

#Load ChiP data

colnames(data_ATAC) <- c("Chr", "Start", "End","IC_4_6_K4me3_1","IC_4_6_K4me3_2","IC_6_8_K4me3_1","IC_6_8_K4me3_2","IC_8_10_K4me3_1","IC_8_10_K4me3_2","VC_4_6_K4me3_1","VC_4_6_K4me3_2","VC_68_K4me3_1_1","VC_68_K4me3_2_1","VC_810_K4me3_1_1","VC_810_K4me3_2_1","IC_4_6_K27ac_1","IC_4_6_K27ac_3","IC_6_8_K27ac_1","IC_6_8_K27ac_3","IC_8_10_K27ac_1","IC_8_10_K27ac_2","VC_4_6_K27ac_1","VC_4_6_K27ac_2","VC_68_K27ac_1_1","VC_68_K27ac_2_1","VC_810_K27ac_1_1","VC_810_K27ac_2_1","IC_4_6_K79me3_1","IC_4_6_K79me3_2","IC_6_8_K79me3_1","IC_6_8_K79me3_2","IC_8_10_K79me3_1","IC_8_10_K79me3_2","VC_4_6_K79me3_1","VC_4_6_K79me3_2","VC_68_K79me3_1_1","VC_68_K79me3_2_1","VC_810_K79me3_1_1","VC_810_K79me3_2_1","IC_4_6_K4mono_1","IC_4_6_K4mono_2","IC_6_8_K4mono_1","IC_6_8_K4mono_2","IC_8_10_K4mono_1","IC_8_10_K4mono_2","VC_4_6_K4mono_1","VC_4_6_K4mono_2","VC_68_K4mono_1_1","VC_68_K4mono_2_1","VC_810_K4mono_1_1","VC_810_K4mono_2_1","IC_4_6_K27me3_1","IC_4_6_K27me3_2","IC_6_8_K27me3_2","IC_6_8_K27me3_3","IC_8_10_K27me3_1","IC_8_10_K27me3_2","VC_4_6_K27me3_1","VC_4_6_K27me3_2","VC_68_K27me3_1_1","VC_68_K27me3_2_1","VC_810_K27me3_1_1","VC_810_K27me3_2_1"
,"Seqname_UTR","Source","Feature","Start_UTR"	,"End_UTR","Score",	"Strand"	,"Frame","Attributes")

colnames(data_ATAC_all) <- c("Chr", "Start", "End","IC_4_6_K4me3_1","IC_4_6_K4me3_2","IC_6_8_K4me3_1","IC_6_8_K4me3_2","IC_8_10_K4me3_1","IC_8_10_K4me3_2","VC_4_6_K4me3_1","VC_4_6_K4me3_2","VC_68_K4me3_1_1","VC_68_K4me3_2_1","VC_810_K4me3_1_1","VC_810_K4me3_2_1","IC_4_6_K27ac_1","IC_4_6_K27ac_3","IC_6_8_K27ac_1","IC_6_8_K27ac_3","IC_8_10_K27ac_1","IC_8_10_K27ac_2","VC_4_6_K27ac_1","VC_4_6_K27ac_2","VC_68_K27ac_1_1","VC_68_K27ac_2_1","VC_810_K27ac_1_1","VC_810_K27ac_2_1","IC_4_6_K79me3_1","IC_4_6_K79me3_2","IC_6_8_K79me3_1","IC_6_8_K79me3_2","IC_8_10_K79me3_1","IC_8_10_K79me3_2","VC_4_6_K79me3_1","VC_4_6_K79me3_2","VC_68_K79me3_1_1","VC_68_K79me3_2_1","VC_810_K79me3_1_1","VC_810_K79me3_2_1","IC_4_6_K4mono_1","IC_4_6_K4mono_2","IC_6_8_K4mono_1","IC_6_8_K4mono_2","IC_8_10_K4mono_1","IC_8_10_K4mono_2","VC_4_6_K4mono_1","VC_4_6_K4mono_2","VC_68_K4mono_1_1","VC_68_K4mono_2_1","VC_810_K4mono_1_1","VC_810_K4mono_2_1","IC_4_6_K27me3_1","IC_4_6_K27me3_2","IC_6_8_K27me3_2","IC_6_8_K27me3_3","IC_8_10_K27me3_1","IC_8_10_K27me3_2","VC_4_6_K27me3_1","VC_4_6_K27me3_2","VC_68_K27me3_1_1","VC_68_K27me3_2_1","VC_810_K27me3_1_1","VC_810_K27me3_2_1"
                         ,"Seqname_UTR","Source","Feature","Start_UTR"	,"End_UTR","Score",	"Strand"	,"Frame","Attributes")


Atributes_col <- as.data.frame(data_ATAC[,72])
Atributes_split <- separate(Atributes_col,1, c("FBgn","Symbol","FBtr"), sep = c(";"), remove = TRUE)
FBgn <- gsub("gene_id ","",Atributes_split$FBgn)
Symbol <- gsub("gene_symbol ","",Atributes_split$Symbol)
FBtr <- gsub("transcript_id ","",Atributes_split$Symbol)

data_ATAC2 <- cbind(data_ATAC[,1:3],Symbol,FBgn,FBtr,data_ATAC[,4:71])


RNA_ChIP_data <- merge(data_ATAC2,VST_counts,by=c("FBgn"),all.x=TRUE)

RNA_ChIP_data <- unique(RNA_ChIP_data)

```

```{r ENHANCERDESEQDATA}

Tissue_46_K4me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_46h_K4me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_68_K4me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_68h_K4me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_810_K4me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_810h_K4me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 

Tissue_46_K27ac <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_46h_K27ac_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_68_K27ac <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_68h_K27ac_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_810_K27ac <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_810h_K27ac_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 

Tissue_46_K79me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_46h_K79me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_68_K79me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_68h_K79me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_810_K79me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_810h_K79me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 

Tissue_46_K4me1 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_46h_K4me1_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_68_K4me1 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_68h_K4me1_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_810_K4me1 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_810h_K4me1_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 

Tissue_46_K27me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_46h_K27me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_68_K27me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_68h_K27me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 
Tissue_810_K27me3 <- read.delim("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/ENHANCER_no_Promoters_no_Exons_DESeq2_results_with_input_count_data_Tissue_810h_K27me3_RNA_seq_VST.csv",stringsAsFactors=F, sep= "\t",header=T) 


``` 

```{r TOP100data}



IC_46_K4me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K4me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_46_K4me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K4me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_68_K4me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K4me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_68_K4me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K4me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_810_K4me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K4me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_810_K4me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K4me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 


IC_46_K27ac <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K27ac_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_46_K27ac <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K27ac_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_68_K27ac <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K27ac_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_68_K27ac <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K27ac_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_810_K27ac <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K27ac_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_810_K27ac <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K27ac_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_46_K79me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K79me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_46_K79me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K79me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_68_K79me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K79me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_68_K79me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K79me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_810_K79me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K79me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_810_K79me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K79me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 


IC_46_K4me1 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K4me1_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_46_K4me1 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K4me1_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_68_K4me1 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K4me1_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_68_K4me1 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K4me1_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_810_K4me1 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K4me1_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_810_K4me1 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K4me1_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_46_K27me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K27me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_46_K27me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_46h_K27me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_68_K27me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K27me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_68_K27me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_68h_K27me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 

IC_810_K27me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K27me3_IC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 
VC_810_K27me3 <- read.table("C:/Users/Admin/Documents/FINAL_REAL_ENHANCER_TISSUE_ANALYIS/Tissue_810h_K27me3_VC_TOP100_basemean10_ENHANCER_no_Promoters_no_Exons.csv",stringsAsFactors=F, sep= "\t",header=T) 




ID_column <- c(  rep("IC_46_K4me3",100),rep("VC_46_K4me3",100),rep("IC_68_K4me3",100),rep("VC_68_K4me3",100),rep("IC_810_K4me3",100),rep("VC_810_K4me3",100),rep("IC_46_K27ac",100),rep("VC_46_K27ac",100),rep("IC_68_K27ac",100),rep("VC_68_K27ac",100),rep("IC_810_K27ac",100),rep("VC_810_K27ac",100),rep("IC_46_K79me3",100),rep("VC_46_K79me3",100),rep("IC_68_K79me3",100),rep("VC_68_K79me3",100),rep("IC_810_K79me3",100),rep("VC_810_K79me3",100),rep("IC_46_K4me1",100),rep("VC_46_K4me1",100),rep("IC_68_K4me1",100),rep("VC_68_K4me1",100),rep("IC_810_K4me1",100),rep("VC_810_K4me1",100),rep("IC_46_K27me3",100),rep("VC_46_K27me3",100),rep("IC_68_K27me3",100),rep("VC_68_K27me3",100),rep("IC_810_K27me3",100),rep("VC_810_K27me3",100)  )



```


```{r CombineTOP, warning=FALSE}



All_top_100 <- rbind.data.frame(IC_46_K4me3,VC_46_K4me3,IC_68_K4me3,VC_68_K4me3,IC_810_K4me3,VC_810_K4me3,
                                IC_46_K27ac,VC_46_K27ac,IC_68_K27ac,VC_68_K27ac,IC_810_K27ac,VC_810_K27ac,
                                IC_46_K79me3,VC_46_K79me3,IC_68_K79me3,VC_68_K79me3,IC_810_K79me3,VC_810_K79me3,
                                IC_46_K4me1,VC_46_K4me1,IC_68_K4me1,VC_68_K4me1,IC_810_K4me1,VC_810_K4me1,
                                IC_46_K27me3,VC_46_K27me3,IC_68_K27me3,VC_68_K27me3,IC_810_K27me3,VC_810_K27me3)


TOP100_file_undup <- cbind(ID_column, All_top_100)

#Muss noch auf duplicate gefiltert werden

TOP100_file <- TOP100_file_undup[!duplicated(TOP100_file_undup[,2:7]), ]


#List of genes and RefSeqs
unique__genes <- as.data.frame(unique(TOP100_file$Symbol))
#unique__genes


#Filter Tissue specific resuts
IC_all_upregulated_100 <- rbind.data.frame(IC_46_K4me3,IC_68_K4me3,IC_810_K4me3,
                                           IC_46_K27ac,IC_68_K27ac,IC_810_K27ac,
                                           IC_46_K79me3,IC_68_K79me3,IC_810_K79me3,
                                           VC_46_K4me1,VC_68_K4me1,VC_810_K4me1,
                                           VC_46_K27me3,VC_68_K27me3,VC_810_K27me3)
IC_all_upregulated_100 <- unique(IC_all_upregulated_100[,2:125])

VC_all_upregulated_100 <- rbind.data.frame(VC_46_K4me3,VC_68_K4me3,VC_810_K4me3,
                                           VC_46_K27ac,VC_68_K27ac,VC_810_K27ac,
                                           VC_46_K79me3,VC_68_K79me3,VC_810_K79me3,
                                           IC_46_K4me1,IC_68_K4me1,IC_810_K4me1,
                                           IC_46_K27me3,IC_68_K27me3,IC_810_K27me3)
VC_all_upregulated_100 <- unique(VC_all_upregulated_100[,2:125])

#VC_all_top_100 <- rbind.data.frame(VC_46_K4me3,VC_68_K4me3,VC_810_K4me3, VC_46_K27ac,VC_68_K27ac,VC_810_K27ac, VC_46_K79me3,VC_68_K79me3,VC_810_K79me3, VC_46_K4me1,VC_68_K4me1,VC_810_K4me1,VC_46_K27me3,VC_68_K27me3,VC_810_K27me3)

#Hey wenn ich alle signifikanten ver채nderungen in einen 3D vector space mappe kann ich Genactivit채t 체ber die 
#Euklidische Distanz vorhersagen. Danke f체r die Inspiration.




VC_all_top_100 <- subset(TOP100_file_undup, log2FoldChange > 0)
IC_all_top_100 <- subset(TOP100_file_undup, log2FoldChange < 0)



#ID_column_VC = c("VC_46_K4me3","VC_68_K4me3","VC_810_K4me3"," VC_46_K27ac","VC_68_K27ac","VC_810_K27ac"," VC_46_K79me3","VC_68_K79me3","VC_810_K79me3","46_K4me1","68_K4me1","810_K4me1","46_K27me3","68_K27me3","810_K27me3") )


num_genes <- length(unique(TOP100_file$Symbol))

num_genes



ChiP_tables_MAT  <- data.matrix(TOP100_file[,8:67]) 

#ChiP_MAT <- na.omit(ChiP_tables_MAT) # listwise deletion of missing
#mydata <- scale(mydata[-1]) # standardize variables 

# Determine number of clusters
wss <- (nrow(ChiP_tables_MAT)-1)*sum(apply(ChiP_tables_MAT,2,var))
for (i in 1:20) wss[i] <- sum(kmeans(ChiP_tables_MAT,
                                     centers=i)$withinss)
plot(1:20, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")


# K-Means Cluster Analysis
fit3 <- kmeans(TOP100_file[,8:67], 6) # 6 cluster solution
# get cluster means
aggregate(TOP100_file,by=list(fit3$cluster),FUN=mean)
# append cluster assignment
TOP100_file_6_kmeans <- data.frame(TOP100_file, fit3$cluster) 
#write.table(mydata, "C:/Users/aglahs/Downloads/TSS_plus_600_kmeans_clustering_7_clusters.txt", sep="\t") 

TOP100_file_6_kmeans <- TOP100_file_6_kmeans[order(TOP100_file_6_kmeans$fit3.cluster),]
#Raw_read_data
heat_data_matrix <- data.matrix(log2(TOP100_file_6_kmeans[8:67]))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix, Rowv=NA, Colv=NA, col=pal, scale="none",  ylab="TSSs")

#RNA_VST_values
heat_data_matrix <- data.matrix(log2(TOP100_file_6_kmeans[76:122]))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix, Rowv=NA, Colv=NA, col=pal, scale="none",  ylab="TSSs")

``` 

```{r TissuePlots1}

library(purrr)


RNA_ChIP_data_new  <- RNA_ChIP_data[order(RNA_ChIP_data$FBgn),]
RNA_ChIP_data_new  <- RNA_ChIP_data[,c(1:67,70:120)]
RNA_ChIP_data_new <- unique(RNA_ChIP_data_new)


#Merge_log2FC_data


TRIERBNF <- merge(RNA_ChIP_data,Tissue_46_K4me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_68_K4me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_810_K4me3[,c(3,4,127)], by=c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_46_K27ac[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- unique(TRIERBNF) 
TRIERBNF <- merge(TRIERBNF,Tissue_68_K27ac[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_810_K27ac[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_46_K79me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_68_K79me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_810_K79me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- unique(TRIERBNF) 
TRIERBNF <- merge(TRIERBNF,Tissue_46_K4me1[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_68_K4me1[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_810_K4me1[,c(3,4,127)], by=c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_46_K27me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- merge(TRIERBNF,Tissue_68_K27me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
TRIERBNF <- unique(TRIERBNF) 
Combined_large_list <- merge(TRIERBNF,Tissue_810_K27me3[,c(3,4,127)], by= c("Start","End"), all.x =T)
Combined_large_list <- unique(Combined_large_list) 


colnames(Combined_large_list)[126:140] <- c("Tissue_46_K4me3","Tissue_68_K4me3","Tissue_810_K4me3","Tissue_46_K27ac","Tissue_68_K27ac","Tissue_810_K27ac","Tissue_46_K79me3","Tissue_68_K79me3","Tissue_810_K79me3","Tissue_46_K4me1","Tissue_68_K4me1","Tissue_810_K4me1","Tissue_46_K27me3","Tissue_68_K27me3","Tissue_810_K27me3")



#Replace all NA with 0
Combined_large_list[,126:140] <- replace(Combined_large_list[,126:140], is.na(Combined_large_list[,126:140]), 0)
#drops <- c("Symbol")
#Combined_large_list <- Combined_large_list[ , !(names(Combined_large_list) %in% drops)]






# K-Means Cluster Analysis
fit3 <- kmeans(Combined_large_list[,126:140], 6) # 6 cluster solution
# get cluster means
aggregate(Combined_large_list,by=list(fit3$cluster),FUN=mean)
# append cluster assignment
All_file_6_kmeans <- data.frame(Combined_large_list, fit3$cluster) 
#write.table(mydata, "C:/Users/aglahs/Downloads/TSS_plus_600_kmeans_clustering_7_clusters.txt", sep="\t") 

All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$fit3.cluster),]

#colnames(All_file_6_kmeans) = c("Fbgn","RefSeqID","Chr","Start","End","Score","Strand","CGID","Tissue_46_K4me3","Tissue_68_K4me3","Tissue_810_K4me3","Tissue_46_K27ac","Tissue_68_K27ac","Tissue_810_K27ac","Tissue_46_K79me3","Tissue_68_K79me3","Tissue_810_K79me3","Tissue_46_K4me1","Tissue_68_K4me1","Tissue_810_K4me1","Tissue_46_K27me3","Tissue_68_K27me3","Tissue_810_K27me3", "kmeans_6")

#Heatmap_kmenas

heat_data_matrix <- data.matrix(All_file_6_kmeans[,126:140])
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix, Rowv=NA, Colv=NA, col=pal, scale="none",  ylab="TSSs", breaks=seq(-3, 3, length.out=101))

heat_data_matrix <- data.matrix(All_file_6_kmeans[7:66])
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix, Rowv=NA, Colv=NA, col=pal, scale="none",  ylab="TSSs", breaks=seq(0, 3000, length.out=101))

heat_data_matrix <- data.matrix(All_file_6_kmeans[75:122])
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix, Rowv=NA, Colv=NA, col=pal, scale="row",  ylab="TSSs")



#Heatmap custom sort

All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_810_K27ac),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_68_K27ac),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_46_K27ac),]

All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_46_K27me3),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_68_K27me3),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_810_K27me3),]

All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_810_K79me3),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_68_K79me3),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_46_K79me3),]

All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_810_K4me3),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_68_K4me3),]
All_file_6_kmeans <- All_file_6_kmeans[order(All_file_6_kmeans$Tissue_46_K4me3),]

heat_data_matrix <- data.matrix(All_file_6_kmeans[126:140])
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix, Rowv=NA, Colv=NA, col=pal, scale="none",  ylab="TSSs", breaks=seq(-3, 3, length.out=101))


```

```{r SpecificResultsTissueEnhancer}


#Alternative_Euklidian_distance

#Combined_temporal_vectors
K4me3_vector = (All_file_6_kmeans$Tissue_46_K4me3 + All_file_6_kmeans$Tissue_68_K4me3 + All_file_6_kmeans$Tissue_810_K4me3)
K27ac_vector = (All_file_6_kmeans$Tissue_46_K27ac + All_file_6_kmeans$Tissue_68_K27ac + All_file_6_kmeans$Tissue_810_K27ac)
K79me3_vector = (All_file_6_kmeans$Tissue_46_K79me3 + All_file_6_kmeans$Tissue_68_K79me3 + All_file_6_kmeans$Tissue_810_K79me3)
K4me1_vector = (All_file_6_kmeans$Tissue_46_K4me1 + All_file_6_kmeans$Tissue_68_K4me1 + All_file_6_kmeans$Tissue_810_K4me1)
K27me3_vector = (All_file_6_kmeans$Tissue_46_K27me3 + All_file_6_kmeans$Tissue_68_K27me3 + All_file_6_kmeans$Tissue_810_K27me3)

Euklidian_dist = sqrt((K27ac_vector*K27ac_vector) + (K79me3_vector*K79me3_vector)+(K4me1_vector*K4me1_vector)+(K27me3_vector*K27me3_vector))

All_file_6_kmeans_euklid <- cbind(All_file_6_kmeans, K4me3_vector, K27ac_vector, K79me3_vector, K4me1_vector, K27me3_vector, Euklidian_dist)


write.table(All_file_6_kmeans_euklid,"ENHANCER_Combined_all_TSS_base_mean_100_with_all_Log2FC_summary_and_euclid.csv", sep = "\t",quote=F, row.names=F)



#Individual vectors
K4em3_46_vector = All_file_6_kmeans$Tissue_46_K4me3
K27ac_46_vector = All_file_6_kmeans$Tissue_46_K27ac 
K79em3_46_vector = All_file_6_kmeans$Tissue_46_K79me3 
K4em1_46_vector = All_file_6_kmeans$Tissue_46_K4me1 
K27me3_46_vector = All_file_6_kmeans$Tissue_46_K27me3 
K4em3_68_vector = All_file_6_kmeans$Tissue_68_K4me3 
K27ac_68_vector = All_file_6_kmeans$Tissue_68_K27ac 
K79em3_68_vector = All_file_6_kmeans$Tissue_68_K79me3 
K4em1_68_vector = All_file_6_kmeans$Tissue_68_K4me1 
K27me3_68_vector = All_file_6_kmeans$Tissue_68_K27me3 
K4em3_810_vector = All_file_6_kmeans$Tissue_810_K4me3
K27ac_810_vector = All_file_6_kmeans$Tissue_810_K27ac
K79em3_810_vector = All_file_6_kmeans$Tissue_810_K79me3
K4em1_810_vector = All_file_6_kmeans$Tissue_810_K4me1
K27me3_810_vector = All_file_6_kmeans$Tissue_810_K27me3


```

```{r Heatmaps}

All_file_6_kmeans_euklid <- All_file_6_kmeans_euklid[order(-All_file_6_kmeans_euklid$Euklidian_dist),]



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euklid[,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euklid$Symbol.x
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs", breaks=seq(-3, 3, length.out=101),Rowv=NA)
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=NA, breaks=seq(0, 5000, length.out=101))
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=NA)
cat('\r\n\r\n')

#Top_results_on_euklid

All_file_6_kmeans_euklid[1:25,5]

heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euklid[1:25,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euklid[1:25,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


```



```{r Top50}

All_file_6_kmeans_euklid[1:50,5]

#Top_results_on_euklid

heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euklid[1:50,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euklid[1:50,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')

```


```{r Top100}

All_file_6_kmeans_euklid[1:100,5]

#Top_results_on_euklid

heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euklid[1:75,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euklid[1:75,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')

```


```{r Reorder_by_K27ac-K27me3}

All_file_6_kmeans_K27 <- cbind(All_file_6_kmeans_euklid, (abs(All_file_6_kmeans_euklid$K27ac_vector - All_file_6_kmeans_euklid$K27me3_vector)))

colnames(All_file_6_kmeans_K27)[148] = c("Combined_K27_vector")

All_file_6_kmeans_K27 <- All_file_6_kmeans_K27[order(-All_file_6_kmeans_K27$Combined_K27_vector),]


All_file_6_kmeans_K27[1:50,5]


#Top_results_on_euklid

heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euklid[1:25,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euklid[1:25,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')






#Top_results_on_euklid

heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euklid[1:50,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euklid[1:50,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')

```

```{r individualTimepointsTOPs}

#Combined_temporal_vectors



#Individual vectors
K4me3_46_vector = All_file_6_kmeans_K27$Tissue_46_K4me3
K27ac_46_vector = All_file_6_kmeans_K27$Tissue_46_K27ac 
K79me3_46_vector = All_file_6_kmeans_K27$Tissue_46_K79me3 
K4me1_46_vector = All_file_6_kmeans_K27$Tissue_46_K4me1 
K27me3_46_vector = All_file_6_kmeans_K27$Tissue_46_K27me3 
K4me3_68_vector = All_file_6_kmeans_K27$Tissue_68_K4me3 
K27ac_68_vector = All_file_6_kmeans_K27$Tissue_68_K27ac 
K79me3_68_vector = All_file_6_kmeans_K27$Tissue_68_K79me3 
K4me1_68_vector = All_file_6_kmeans_K27$Tissue_68_K4me1 
K27me3_68_vector = All_file_6_kmeans_K27$Tissue_68_K27me3 
K4me3_810_vector = All_file_6_kmeans_K27$Tissue_810_K4me3
K27ac_810_vector = All_file_6_kmeans_K27$Tissue_810_K27ac
K79me3_810_vector = All_file_6_kmeans_K27$Tissue_810_K79me3
K4me1_810_vector = All_file_6_kmeans_K27$Tissue_810_K4me1
K27me3_810_vector = All_file_6_kmeans_K27$Tissue_810_K27me3

Euklidian_dist_46 = sqrt((K27ac_46_vector*K27ac_46_vector) + (K79me3_46_vector*K79me3_46_vector)+(K4me1_46_vector*K4me1_46_vector)+(K27me3_46_vector*K27me3_46_vector))

Euklidian_dist_68 = sqrt((K27ac_68_vector*K27ac_68_vector) + (K79me3_68_vector*K79me3_68_vector)+(K4me1_68_vector*K4me1_68_vector)+(K27me3_68_vector*K27me3_68_vector))

Euklidian_dist_810 = sqrt((K27ac_810_vector*K27ac_810_vector) + (K79me3_810_vector*K79me3_810_vector)+(K4me1_810_vector*K4me1_810_vector)+(K27me3_810_vector*K27me3_810_vector))

All_file_6_kmeans_euk_K27_temp <- cbind(All_file_6_kmeans_K27, Euklidian_dist_46, Euklidian_dist_68, Euklidian_dist_810)





colnames(All_file_6_kmeans_euk_K27_temp)[149:151] = c("Euk46","Euk68","Euk810")



write.table(All_file_6_kmeans_euk_K27_temp,"ENHANCER_Combined_all_TSS_base_mean_100_with_all_Log2FC_summary_and_euclid_K27vector_temp_sep.csv", sep = "\t",quote=F, row.names=F)


```

```{r Euklid46hours}

All_file_6_kmeans_euk_K27_temp <- All_file_6_kmeans_euk_K27_temp[order(-All_file_6_kmeans_euk_K27_temp$Euk46),]



All_file_6_kmeans_euk_K27_temp[1:100,5]



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_temp[1:40,]$Symbol.x
#Top_results_on 46 euklid
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,c(109,112,115,118,121)])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,c(109,112,115,118,121)], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_temp[1:40,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')



```

```{r Euklid68h}

All_file_6_kmeans_euk_K27_temp <- All_file_6_kmeans_euk_K27_temp[order(-All_file_6_kmeans_euk_K27_temp$Euk68),]


All_file_6_kmeans_euk_K27_temp[1:100,5]


heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_temp[1:40,]$Symbol.x
#Top_results_on 46 euklid
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,c(110,113,116,119,122)])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,c(110,113,116,119,122)], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_temp[1:40,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')

```

```{r Eklid810h}


All_file_6_kmeans_euk_K27_temp <- All_file_6_kmeans_euk_K27_temp[order(-All_file_6_kmeans_euk_K27_temp$Euk810),]


All_file_6_kmeans_euk_K27_temp[1:100,5]



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_temp[1:40,]$Symbol.x
#Top_results_on 46 euklid
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,c(111,114,117,120,123)])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,c(111,114,117,120,123)], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_temp[1:40,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')



```

```{r TemporalseperatedVectors}

All_file_6_kmeans_euk_K27_EUtemp_K27temp <- cbind(All_file_6_kmeans_euk_K27_temp, (abs(All_file_6_kmeans_euk_K27_temp$Tissue_46_K27ac - All_file_6_kmeans_euklid$Tissue_46_K27me3)))

colnames(All_file_6_kmeans_euk_K27_EUtemp_K27temp)[152] = c("K27_vector_46h")

All_file_6_kmeans_euk_K27_EUtemp_K27temp <- cbind(All_file_6_kmeans_euk_K27_EUtemp_K27temp, (abs(All_file_6_kmeans_euk_K27_EUtemp_K27temp$Tissue_68_K27ac - All_file_6_kmeans_euk_K27_EUtemp_K27temp$Tissue_68_K27me3)))

colnames(All_file_6_kmeans_euk_K27_EUtemp_K27temp)[153] = c("K27_vector_68h")

All_file_6_kmeans_euk_K27_EUtemp_K27temp <- cbind(All_file_6_kmeans_euk_K27_EUtemp_K27temp, (abs(All_file_6_kmeans_euk_K27_EUtemp_K27temp$Tissue_810_K27ac - All_file_6_kmeans_euk_K27_EUtemp_K27temp$Tissue_810_K27me3)))

colnames(All_file_6_kmeans_euk_K27_EUtemp_K27temp)[154] = c("K27_vector_810h")


#Sort by K27vector and plot

All_file_6_kmeans_euk_K27_EUtemp_K27temp <- All_file_6_kmeans_euk_K27_EUtemp_K27temp[order(-All_file_6_kmeans_euk_K27_EUtemp_K27temp$K27_vector_46h),]


All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:100,5]



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:40,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')

#Sort by 68h K27 vector

All_file_6_kmeans_euk_K27_EUtemp_K27temp <- All_file_6_kmeans_euk_K27_EUtemp_K27temp[order(-All_file_6_kmeans_euk_K27_EUtemp_K27temp$K27_vector_68h),]


All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:100,5]



heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:40,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(log2(heat_data_matrix_euklid[,1:60]), Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')

#Sort by 810h K27 vector

All_file_6_kmeans_euk_K27_EUtemp_K27temp <- All_file_6_kmeans_euk_K27_EUtemp_K27temp[order(-All_file_6_kmeans_euk_K27_EUtemp_K27temp$K27_vector_810h),]


All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:100,5]

write.table(All_file_6_kmeans_euk_K27_EUtemp_K27temp,"ENHANCER_Combined_all_TSS_base_mean_100_with_all_Log2FC_summary_and_euclid_K27vector_temp_sep_K27vectortemp_Complete.csv", sep = "\t",quote=F, row.names=F)


heat_data_matrix_euklid <- data.matrix(All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:40,c(7:66,75:122,126:140)])
row.names(heat_data_matrix_euklid) <- All_file_6_kmeans_euk_K27_EUtemp_K27temp[1:40,]$Symbol.x
dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,109:123])))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(log2(heat_data_matrix_euklid[,1:60]), Colv=NA, col=pal, scale="none",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="TSSs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')




```

```{r loadGranges,  warning=FALSE, message=FALSE}
#source("https://bioconductor.org/biocLite.R")
BiocManager::install("GenomicRanges")
library("GenomicRanges")
library("ChIPpeakAnno")

```


```{r readHMMtables}


#Load and grange object transformation

S10_50_master <- read.table("C:/Users/Admin/Documents/S10_50_master_file.bed",sep="\t",header=T,stringsAsFactors = FALSE)

gr_States <- makeGRangesFromDataFrame(S10_50_master, keep.extra.columns=TRUE)

AAA_Master <- cbind(All_file_6_kmeans_euk_K27_EUtemp_K27temp[,c(4,1:3,5:154)])

gr_promoters <- makeGRangesFromDataFrame(AAA_Master, keep.extra.columns=TRUE)





```

```{r Granges}


library(dplyr)

IC_46_promoter_state_regions <- filter(filter(S10_50_master, IC_46h == 4),VC_46h ==5)
IC_68_promoter_state_regions <- filter(filter(S10_50_master, IC_68h == 4),VC_68h ==5)
IC_810_promoter_state_regions <- filter(filter(S10_50_master, IC_810h == 4),VC810h ==5)

VC_46_promoter_state_regions <- filter(filter(S10_50_master, VC_46h == 4),IC_46h ==5)
VC_68_promoter_state_regions <- filter(filter(S10_50_master, VC_68h == 4),IC_68h ==5)
VC_810_promoter_state_regions <- filter(filter(S10_50_master, VC810h == 4),IC_810h ==5)


#All active genes for GO Analysis background



gr_IC_46_active_pr <- makeGRangesFromDataFrame(IC_46_promoter_state_regions, keep.extra.columns=TRUE)
countedoverl <- sum( countOverlaps(gr_promoters, gr_IC_46_active_pr))
print("IC_46:")
print(countedoverl)
#Subset hits and convert to dataframe
subset_IC_46_pr_active_str <- as(subsetByOverlaps(gr_promoters, gr_IC_46_active_pr),"data.frame")
write.table(subset_IC_46_pr_active_str, "IC_active_stringent_46_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

gr_IC_68_active_pr <- makeGRangesFromDataFrame(IC_68_promoter_state_regions, keep.extra.columns=TRUE)
countedoverl <- sum( countOverlaps(gr_promoters, gr_IC_68_active_pr))
print("IC_68:")
print(countedoverl)
#Subset hits and convert to dataframe
subset_IC_68_pr_active_str <- as(subsetByOverlaps(gr_promoters, gr_IC_68_active_pr),"data.frame")
write.table(subset_IC_68_pr_active_str, "IC_active_stringent_68_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

gr_IC_810_active_pr <- makeGRangesFromDataFrame(IC_810_promoter_state_regions, keep.extra.columns=TRUE)
countedoverl <- sum( countOverlaps(gr_promoters, gr_IC_810_active_pr))
print("IC_810:")
print(countedoverl)
#Subset hits and convert to dataframe
subset_IC_810_pr_active_str <- as(subsetByOverlaps(gr_promoters, gr_IC_810_active_pr),"data.frame")
write.table(subset_IC_810_pr_active_str, "IC_active_stringent_810_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)


gr_VC_46_active_pr <- makeGRangesFromDataFrame(VC_46_promoter_state_regions, keep.extra.columns=TRUE)
countedoverl <- sum( countOverlaps(gr_promoters, gr_VC_46_active_pr))
print("VC_46:")
print(countedoverl)
#Subset hits and convert to dataframe
subset_VC_46_pr_active_str <- as(subsetByOverlaps(gr_promoters, gr_VC_46_active_pr),"data.frame")
write.table(subset_VC_46_pr_active_str, "VC__active_stringent_46_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

gr_VC_68_active_pr <- makeGRangesFromDataFrame(VC_68_promoter_state_regions, keep.extra.columns=TRUE)
countedoverl <- sum( countOverlaps(gr_promoters, gr_VC_68_active_pr))
print("VC_68:")
print(countedoverl)
#Subset hits and convert to dataframe
subset_VC_68_pr_active_str <- as(subsetByOverlaps(gr_promoters, gr_VC_68_active_pr),"data.frame")
write.table(subset_VC_68_pr_active_str, "VC_active_stringent_68_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

gr_VC_810_active_pr <- makeGRangesFromDataFrame(VC_810_promoter_state_regions, keep.extra.columns=TRUE)
countedoverl <- sum( countOverlaps(gr_promoters, gr_VC_810_active_pr))
print("VC_810:")
print(countedoverl)
#Subset hits and convert to dataframe
subset_VC_810_pr_active_str <- as(subsetByOverlaps(gr_promoters, gr_VC_810_active_pr),"data.frame")
write.table(subset_VC_810_pr_active_str, "VC_active_stringent_810_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)





#Subset not overlaping genes from all active genes
#Tissue comparison
uniques_VC_46 <- setdiff(subsetByOverlaps(gr_promoters,gr_VC_46_active_pr),subsetByOverlaps(gr_promoters,gr_IC_46_active_pr))
uniques_out <- as(uniques_VC_46,"data.frame")
write.table(uniques_out, "Uniques_VC_vs_IC_46_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

uniques_out[,1:7]

uniques_VC_68 <- setdiff(subsetByOverlaps(gr_promoters,gr_VC_68_active_pr),subsetByOverlaps(gr_promoters,gr_IC_68_active_pr))
uniques_out <- as(uniques_VC_68,"data.frame")
write.table(uniques_out, "Uniques_VC_vs_IC_68_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

uniques_out[,1:7]

uniques_VC_810 <- setdiff(subsetByOverlaps(gr_promoters,gr_VC_810_active_pr),subsetByOverlaps(gr_promoters,gr_IC_810_active_pr))
uniques_out <- as(uniques_VC_810,"data.frame")
write.table(uniques_out, "Uniques_VC_vs_IC_810_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

uniques_out[,1:7]

uniques_IC_46 <- setdiff(subsetByOverlaps(gr_promoters,gr_IC_46_active_pr),subsetByOverlaps(gr_promoters,gr_VC_46_active_pr))
uniques_out <- as(uniques_IC_46,"data.frame")
write.table(uniques_out, "Uniques_IC_vs_VC_46_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

uniques_out[,1:7]

uniques_IC_68 <- setdiff(subsetByOverlaps(gr_promoters,gr_IC_68_active_pr),subsetByOverlaps(gr_promoters,gr_VC_68_active_pr))
uniques_out <- as(uniques_IC_68,"data.frame")
write.table(uniques_out, "Uniques_IC_vs_VC_68_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

uniques_out[,1:7]

uniques_IC_810 <- setdiff(subsetByOverlaps(gr_promoters,gr_IC_810_active_pr),subsetByOverlaps(gr_promoters,gr_VC_810_active_pr))
uniques_out <- as(uniques_IC_810,"data.frame")
write.table(uniques_out, "Uniques_IC_vs_VC_810_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

uniques_out[,1:7]

shared_uniques_IC <- subsetByOverlaps(uniques_IC_810, subsetByOverlaps(uniques_IC_46,uniques_IC_68))
shared_uniques_IC_df <- as(shared_uniques_IC,"data.frame")
write.table(shared_uniques_IC_df, "shared_Uniques_IC_betw_each_timep_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

shared_uniques_IC_df[,1:7]

shared_uniques_VC <- subsetByOverlaps(uniques_VC_810, subsetByOverlaps(uniques_VC_46,uniques_VC_68))
shared_uniques_VC_df <- as(shared_uniques_VC,"data.frame")
write.table(shared_uniques_VC_df, "shared_Uniques_VC_betw_each_timep_active_enh_4to5.bed", col.names=TRUE, sep="\t",row.names=FALSE,quote=FALSE)

shared_uniques_VC_df[,1:7]

#VENN DIAGRAMM

gr_act_pr_IC_46 <- subsetByOverlaps(gr_promoters, gr_IC_46_active_pr)

gr_act_pr_IC_68 <- subsetByOverlaps(gr_promoters, gr_IC_68_active_pr)

gr_act_pr_IC_810 <- subsetByOverlaps(gr_promoters, gr_IC_810_active_pr)

gr_act_pr_VC_46 <- subsetByOverlaps(gr_promoters, gr_VC_46_active_pr)

gr_act_pr_VC_68 <- subsetByOverlaps(gr_promoters, gr_VC_68_active_pr)

gr_act_pr_VC_810 <- subsetByOverlaps(gr_promoters, gr_VC_810_active_pr)



IC_res <- makeVennDiagram(Peaks=list(gr_act_pr_IC_46,gr_act_pr_IC_68, gr_act_pr_IC_810),
                          
                          NameOfPeaks=c("IC_46", "IC_68","IC_810"))

VC_res <- makeVennDiagram(Peaks=list(gr_act_pr_VC_46,gr_act_pr_VC_68, gr_act_pr_VC_810),
                          
                          NameOfPeaks=c("VC_46", "VC_68","VC_810"))


tissue_res <- makeVennDiagram(Peaks=list(gr_act_pr_VC_46,gr_act_pr_IC_46, gr_act_pr_VC_68,gr_act_pr_IC_68),
                              
                              NameOfPeaks=c("VC_46", "IC_46","VC_68", "IC_68"))



```
```{r IntegrateHMM}

library(bedr)


Intersect_master_states <- subsetByOverlaps(gr_States, gr_promoters)

Intersect_master <- mergeByOverlaps(gr_States, gr_promoters)

#IC46enh <- Intersect_master[ Intersect_master$IC_46h == 4, ]
#IC46enh <- Intersect_master[ IC46enh$VC_46h == 5, ]

#IC68enh <- Intersect_master[ Intersect_master$IC_68h == 4, ]
#IC68enh <- Intersect_master[ IC68enh$VC_68h == 5, ]

#IC810enh <- Intersect_master[ Intersect_master$IC_810h == 4, ]
#IC810enh <- Intersect_master[ IC810enh$VC810h == 5, ]


#unique(IC46enh$gr_promoters$Symbol.x)

#unique(IC68enh$gr_promoters$Symbol.x)

#unique(IC810enh$gr_promoters$Symbol.x)


#VC46enh <- Intersect_master[ Intersect_master$VC_46h == 4, ]
#VC46enh <- Intersect_master[ VC46enh$IC_46h == 5, ]

#VC68enh <- Intersect_master[ Intersect_master$VC_68h == 4, ]
#VC68enh <- Intersect_master[ VC68enh$IC_68h == 5, ]

#VC810enh <- Intersect_master[ Intersect_master$VC810h == 4, ]
#VC810enh <- Intersect_master[ VC810enh$IC_810h == 5, ]


#unique(VC46enh$gr_promoters$Symbol.x)

#unique(VC68enh$gr_promoters$Symbol.x)

#unique(VC810enh$gr_promoters$Symbol.x)

#gr_IC46enh <-  unique(IC46enh$gr_promoters)

#gr_IC68enh <-  unique(IC68enh$gr_promoters)

#gr_IC810enh <-  unique(IC810enh$gr_promoters)


#gr_VC46enh <-  unique(VC46enh$gr_promoters)

#gr_VC68enh <-  unique(VC68enh$gr_promoters)

#gr_VC810enh <-  unique(VC810enh$gr_promoters)


Venn_enhancer_VC <- makeVennDiagram(Peaks=list(gr_act_pr_VC_46,gr_act_pr_VC_68, gr_act_pr_VC_810),
                          
                          NameOfPeaks=c("VC_46", "VC_68","VC_810"))


Venn_enhancer_VC <- makeVennDiagram(Peaks=list(gr_act_pr_IC_46,gr_act_pr_IC_68, gr_act_pr_IC_810),
                          
                          NameOfPeaks=c("IC_46", "IC_68","IC_810"))

#Shared hit genes Check out the cadherin complex


shared_uniques_VC <- subsetByOverlaps(gr_act_pr_VC_46, subsetByOverlaps(gr_act_pr_VC_68,gr_act_pr_VC_810))
shared_uniques_VC_df <- as(shared_uniques_VC,"data.frame")
shared_uniques_VC_df[1:7]
shared_uniques_VC610 <- subsetByOverlaps(gr_act_pr_VC_68,gr_act_pr_VC_810)
shared_uniques_VC_6to10 <- as(shared_uniques_VC610,"data.frame")
shared_uniques_VC_6to10[1:7]
shared_uniques_VC48 <- subsetByOverlaps(gr_act_pr_VC_46,gr_act_pr_VC_68)
shared_uniques_VC_4to8 <- as(shared_uniques_VC48,"data.frame")
shared_uniques_VC_4to8[1:7]
shared_uniques_VC410 <- subsetByOverlaps(gr_act_pr_VC_46,gr_act_pr_VC_810)
shared_uniques_VC_4to10 <- as(shared_uniques_VC410,"data.frame")
shared_uniques_VC_4to10[1:7]


heat_data_matrix_euklid <- data.matrix(as.data.frame(shared_uniques_VC_df[,c(9:68,76:123,127:141)]))
row.names(heat_data_matrix_euklid) <- shared_uniques_VC_df$Symbol.x
dd <- as.dendrogram(hclust(dist(as.data.frame(shared_uniques_VC_df[,127:141]))))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="CRMs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="CRMs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="CRMs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


shared_uniques_IC <- subsetByOverlaps(gr_act_pr_IC_46, subsetByOverlaps(gr_act_pr_IC_68,gr_act_pr_IC_810))
shared_uniques_IC_df <- as(shared_uniques_IC,"data.frame")
shared_uniques_IC_df[1:7]
shared_uniques_IC610 <- subsetByOverlaps(gr_act_pr_IC_68,gr_act_pr_IC_810)
shared_uniques_IC_6to10 <- as(shared_uniques_IC610,"data.frame")
shared_uniques_IC_6to10[1:7]
shared_uniques_IC48 <- subsetByOverlaps(gr_act_pr_IC_46,gr_act_pr_IC_68)
shared_uniques_IC_4to8 <- as(shared_uniques_IC48,"data.frame")
shared_uniques_IC_4to8[1:7]
shared_uniques_IC410 <- subsetByOverlaps(gr_act_pr_IC_46,gr_act_pr_IC_810)
shared_uniques_IC_4to10 <- as(shared_uniques_IC410,"data.frame")
shared_uniques_IC_4to10[1:7]



heat_data_matrix_euklid <- data.matrix(as.data.frame(shared_uniques_IC_df[,c(9:68,76:123,127:141)]))
row.names(heat_data_matrix_euklid) <- shared_uniques_IC_df$Symbol.x
dd <- as.dendrogram(hclust(dist(as.data.frame(shared_uniques_IC_df[,127:141]))))
redgreen <- c("blue","white", "red") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,109:123], Colv=NA, col=pal, scale="none",  ylab="CRMs",Rowv=dd,keep.dendro=T, breaks=seq(-3, 3, length.out=101))
cat('\r\n\r\n')

#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,1:60], Colv=NA, col=pal, scale="none",  ylab="CRMs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


#heat_data_matrix_euklid <- data.matrix(unique_Combined_TOP100_and_all_TSS[1:25,c(8:117,121:135)])
#row.names(heat_data_matrix_euklid) <- unique_Combined_TOP100_and_all_TSS[1:25,]$Symbol
#dd <- as.dendrogram(hclust(dist(heat_data_matrix_euklid[,111:125])))
redgreen <- c("white", "blue") 
pal <- colorRampPalette(redgreen)(100)
heatmap(heat_data_matrix_euklid[,61:108], Colv=NA, col=pal, scale="row",  ylab="CRMs",Rowv=dd,keep.dendro=T)
cat('\r\n\r\n')


par( mfrow = c( 1, 4 ) )
par(las=2)
par(mar=c(10, 4, 0.5, 1))
boxplot(log2(((shared_uniques_IC_df[,78]+shared_uniques_IC_df[,79])/2)/((shared_uniques_IC_df[,86]+shared_uniques_IC_df[,87])/2)),ylim=c(-0.35,0.25))
abline(h = 0, col = "red")

par(las=2)
par(mar=c(10, 4, 0.5, 1))
boxplot(log2(((shared_uniques_IC_df[,82]+shared_uniques_IC_df[,83])/2)/((shared_uniques_IC_df[,90]+shared_uniques_IC_df[,91])/2)),ylim=c(-0.35,0.25))
abline(h = 0, col = "red")


par(las=2)
par(mar=c(10, 4, 0.5, 1))
boxplot(log2(((shared_uniques_VC_df[,78]+shared_uniques_VC_df[,79])/2)/((shared_uniques_VC_df[,86]+shared_uniques_VC_df[,87])/2)),ylim=c(-0.35,0.25))
abline(h = 0, col = "red")

par(las=2)
par(mar=c(10, 4, 0.5, 1))
boxplot(log2(((shared_uniques_VC_df[,82]+shared_uniques_VC_df[,83])/2)/((shared_uniques_VC_df[,90]+shared_uniques_VC_df[,91])/2)),ylim=c(-0.35,0.25))
abline(h = 0, col = "red")




#IC over neg
par( mfrow = c( 1, 2 ) )
par(las=2)
par(mar=c(10, 4, 0.5, 1))
boxplot(log2(((shared_uniques_IC_df[,78]+shared_uniques_IC_df[,79])/2)/((shared_uniques_IC_df[,76]+shared_uniques_IC_df[,77])/2)),ylim=c(-0.1,0.35))
abline(h = 0, col = "red")

#VC over neg
par(las=2)
par(mar=c(10, 4, 0.5, 1))
boxplot(log2(((shared_uniques_VC_df[,86]+shared_uniques_VC_df[,87])/2)/((shared_uniques_VC_df[,84]+shared_uniques_VC_df[,85])/2)),ylim=c(-0.1,0.35))
abline(h = 0, col = "red")



```

