---
title: "RNA Seq DeSEQ Alex"
author: "Alexander Glahs"
date: "14 Juni 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r Load_libraries, warning=FALSE, message=FALSE}
##Prepare Data
#Load and Process data
#setwd("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/")
#source("https://bioconductor.org/biocLite.R")


library(DESeq2)
#biocLite("stringi")
library(dplyr)
#library(ggplot2)
#library(markdown)
library(knitr)
library(png)      
#Load VST data
library(BiocStyle)
library(rmarkdown)
library(geneplotter)
library(ggplot2)
library(plyr)
library(LSD)
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(stringr)
library(topGO)
library(genefilter)
library(biomaRt)
library(dplyr)
library(EDASeq)
library(fdrtool)
library(kableExtra)
library(knitr)
library(tidyr)
library(made4)
library(corrplot)

options(scipen=999)
```




```{r LoadRNA}
options(scipen=999)
IC_46_neg_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Ind-neg_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

IC_46_neg_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Ind-neg_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

IC_46_pos_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Ind-pos_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

IC_46_pos_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Ind-pos_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_46_neg_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Vnd-neg_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_46_neg_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Vnd-neg_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_46_pos_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Vnd-pos_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_46_pos_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/4-6h_Vnd-pos_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 




IC_68_neg_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Ind-neg_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

IC_68_neg_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Ind-neg_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

IC_68_pos_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Ind-pos_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

IC_68_pos_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Ind-pos_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_68_neg_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Vnd-neg_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_68_neg_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Vnd-neg_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_68_pos_1 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Vnd-pos_1.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 

VC_68_pos_2 <- read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/6-8h_Vnd-pos_2.quant.sf",stringsAsFactors=F, sep= "\t",header=TRUE) 


RNA_NumReads <- cbind(IC_46_neg_1[,c(1:2,5)],IC_46_neg_2[,c(5)],IC_46_pos_1[,c(5)],IC_46_pos_2[,c(5)],VC_46_neg_1[,c(5)],VC_46_neg_2[,c(5)],VC_46_pos_1[,c(5)],VC_46_pos_2[,c(5)],   IC_68_neg_1[,c(5)],IC_68_neg_2[,c(5)],IC_68_pos_1[,c(5)],IC_68_pos_2[,c(5)],VC_68_neg_1[,c(5)],VC_68_neg_2[,c(5)],VC_68_pos_1[,c(5)],VC_68_pos_2[,c(5)])

colnames(RNA_NumReads) <- c("FBtr","length","IC_46_neg_1","IC_46_neg_2","IC_46_pos_1","IC_46_pos_2",   "VC_46_neg_1","VC_46_neg_2","VC_46_pos_1","VC_46_pos_2",  "IC_68_neg_1","IC_68_neg_2","IC_68_pos_1","IC_68_pos_2",   "VC_68_neg_1","VC_68_neg_2","VC_68pos_1","VC_68_pos_2")
options(scipen=999)

RNA_NumReads[,c(3:18)] <- round(RNA_NumReads[,c(3:18)], digits = 0)



#Load ID table
ID_table <-  read.table("C:/Users/Admin/Documents/Name_conversion_NM_FbGn_complete_unirot-gene_ID_master_list.csv",stringsAsFactors=F, sep= "\t",header=TRUE) 

l <- strsplit(as.character(ID_table$RefSeqID), ',')
ID_table_2 <- data.frame(Name = unlist(l), Name.string = rep(ID_table$RefSeqID, lengths(l)))
colnames(ID_table_2) <- c("RefSeq","RefSeqID")

ID_table_long <- merge(ID_table_2,ID_table,by=c("RefSeqID"),all=TRUE)

ID_table_long <- ID_table_long[!duplicated(ID_table_long[,c(2,4)]), ]
colnames(ID_table_long) <- c("All_RefSeq", "RefSeqID","Gene","FBgn")
ID_table_long$All_RefSeq <- paste0("'","'", ID_table_long$All_RefSeq, "'","'")
ID_table_long$Gene <- paste0("'","'", ID_table_long$Gene, "'","'")

ID_FBtr_table <-  read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/FlyBase_IDs_coversion_table_complete.txt",stringsAsFactors=F, sep= "\t",header=TRUE) 
colnames(ID_FBtr_table) <- c("FBtr","FBtr2", "FBgn","name")

```



```{r DeSEQ}
options(scipen=999)
#DESEQ
#Prepare and choose datasets
countData <- RNA_NumReads[,c(5,6,3,4)]
colnames(countData) <- c("IC_1","IC_2","VC_1","VC_2")

colData <- as.matrix(c("IC","IC","VC","VC"),ncol=1)
rownames(colData) <- colnames(countData)
colnames(colData) <- c("sort")

dds <- DESeqDataSetFromMatrix(countData=countData,colData=colData,design = ~ sort)

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

#Filter low count bins
idx_filter <- rowSums( counts(dds, normalized=TRUE) >= 10 ) >= 2
dds <- dds[idx_filter,]

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

RNA_ChIP_data_filter <- cbind(RNA_NumReads,idx_filter)
RNA_ChIP_data_filter <- RNA_ChIP_data_filter[idx_filter,]

#DESEQ2 COMMAND

colData(dds)$sort <- factor(colData(dds)$sort,levels=c("IC","VC"))
dds <- DESeq(dds)

#Results
res <- results(dds)

#Histogram of p-values
hist(res$pvalue, col = "royalblue4", 
      xlab = "p-values",breaks=20)

cat('\r\n\r\n')
#P-value correction with BH method

res <- res[, -which(names(res) == "padj")]

FDR.DESeq2Res <- fdrtool(res$stat, statistic= "normal", plot = T)

cat('\r\n\r\n')

FDR.DESeq2Res$param[1, "sd"]

cat('\r\n\r\n')

res[,"padj"]  <- p.adjust(FDR.DESeq2Res$pval, method = "fdr")

hist(res$padj, col = "royalblue4", 
      xlab = "CORRECTED p-values",breaks=20)

cat('\r\n\r\n')

#colnames(data) <- c("chr","start","end","name","score","strand","IC_4_6_K4me3_1_dm6", "IC_4_6_K4me3_2_dm6", "IC_6_8_K4me3_1_dm6", "IC_6_8_K4me3_2_dm6", "IC_8_10_K4me3_1_dm6", "IC_8_10_K4me3_2_dm6","VC_4_6_K4me3_1_dm6","VC_4_6_K4me3_2_dm6", "VC_68_K4me3_1", "VC_68_K4me3_2", "VC_810_K4me3_1", "VC_810_K4me3_2", "IC_4_6_K27ac_1_dm6", "IC_4_6_K27ac_3", "IC_6_8_K27ac_1_dm6","IC_6_8_K27ac_3_dm6", "IC_8_10_K27ac_1_dm6", "IC_8_10_K27ac_2_dm6", "VC_4_6_K27ac_1_dm6", "VC_4_6_K27ac_2_dm6", "VC_68_K27ac_1", "VC_68_K27ac_2", "VC_810_K27ac_1", "VC_810_K27ac_2", "IC_4_6_K79me3_1_dm6", "IC_4_6_K79me3_2_dm6", "IC_6_8_K79me3_1_dm6", "IC_6_8_K79me3_2_dm6", "IC_8_10_K79me3_1_dm6", "IC_8_10_K79me3_2_dm6", "VC_4_6_K79me3_1_dm6", "VC_4_6_K79me3_2_dm6", "VC_68_K79me3_1", "VC_68_K79me3_2", "VC_810_K79me3", "VC_810_K79me3_2", "IC_4_6_K4mono_1_dm6", "IC_4_6_K4mono_2_dm6", "IC_6_8_K4mono_1_dm6", "IC_6_8_K4mono_2_dm6", "IC_8_10_K4mono_1_dm6", "IC_8_10_K4mono_2_dm6", "VC_4_6_K4mono_1_dm6", "VC_4_6_K4mono_2_dm6", "VC_68_K4mono_1", "VC_68_K4mono_2", "VC_810_K4mono_1", "VC_810_K4mono_2", "IC_4_6_K27me3_1_dm6", "IC_4_6_K27me3_2_dm6", "IC_6_8_K27me3_2_dm6", "IC_6_8_K27me3_3_dm6", "IC_8_10_K27me3_1_dm6", "IC_8_10_K27me3_2_dm6", "VC_4_6_K27me3_1_dm6", "VC_4_6_K27me3_2_dm6", "VC_68_K27me3_1", "VC_68_K27me3_2", "VC_810_K27me3_1", "VC_810_K27me3_2")



filtered_res <- as.data.frame(res)

input_and_res <- cbind(RNA_ChIP_data_filter,as.data.frame(res))
input_and_res$idx_filter <- NULL




write.table(input_and_res,"DESeq2_results_RNAseq_Alex_46h_IC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

write.table(as.data.frame(mcols(dds,use.names=TRUE)),"DESeq2_additional_results_RNAseq_Alex_46h_IC_vs_NEG.txt",sep="\t",quote=F, row.names=F)
write.table(counts(dds, normalized=TRUE),"sizeNorm_counts_DESeq2_results_RNAseq_Alex_46h_IC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

#png(filename="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot.png",width=900,height=600)
par(mar=c(5,5,2,2),cex=1.5,cex.axis=1.3,cex.lab=1.5)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)
dev.off()

#pdf(file="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot_pdf.pdf",width=9,height=6)
par(mar=c(5,5,2,2),cex=1.3,cex.axis=1.1,cex.lab=1.3)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)
dev.off()


IC46 <- as.data.frame(cbind(input_and_res$FBtr, input_and_res$log2FoldChange, input_and_res$padj))
colnames(IC46) <- c("FBtr","log2FC_IC46vsNEG","padj_IC46vsNEG")


```

```{r DeSEQVC46neg}
options(scipen=999)
#DESEQ
#Prepare and choose datasets
countData <- RNA_NumReads[,c(9,10,7,8)]
colnames(countData) <- c("IC_1","IC_2","VC_1","VC_2")

colData <- as.matrix(c("IC","IC","VC","VC"),ncol=1)
rownames(colData) <- colnames(countData)
colnames(colData) <- c("sort")

dds <- DESeqDataSetFromMatrix(countData=countData,colData=colData,design = ~ sort)

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

#Filter low count bins
idx_filter <- rowSums( counts(dds, normalized=TRUE) >= 10 ) >= 2
dds <- dds[idx_filter,]

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

RNA_ChIP_data_filter <- cbind(RNA_NumReads,idx_filter)
RNA_ChIP_data_filter <- RNA_ChIP_data_filter[idx_filter,]

#DESEQ2 COMMAND

colData(dds)$sort <- factor(colData(dds)$sort,levels=c("IC","VC"))
dds <- DESeq(dds)

#Results
res <- results(dds)

#Histogram of p-values
hist(res$pvalue, col = "royalblue4", 
      xlab = "p-values",breaks=20)

cat('\r\n\r\n')
#P-value correction with BH method

res <- res[, -which(names(res) == "padj")]

FDR.DESeq2Res <- fdrtool(res$stat, statistic= "normal", plot = T)

cat('\r\n\r\n')

FDR.DESeq2Res$param[1, "sd"]

cat('\r\n\r\n')

res[,"padj"]  <- p.adjust(FDR.DESeq2Res$pval, method = "fdr")

hist(res$padj, col = "royalblue4", 
      xlab = "CORRECTED p-values",breaks=20)

cat('\r\n\r\n')

#colnames(data) <- c("chr","start","end","name","score","strand","IC_4_6_K4me3_1_dm6", "IC_4_6_K4me3_2_dm6", "IC_6_8_K4me3_1_dm6", "IC_6_8_K4me3_2_dm6", "IC_8_10_K4me3_1_dm6", "IC_8_10_K4me3_2_dm6","VC_4_6_K4me3_1_dm6","VC_4_6_K4me3_2_dm6", "VC_68_K4me3_1", "VC_68_K4me3_2", "VC_810_K4me3_1", "VC_810_K4me3_2", "IC_4_6_K27ac_1_dm6", "IC_4_6_K27ac_3", "IC_6_8_K27ac_1_dm6","IC_6_8_K27ac_3_dm6", "IC_8_10_K27ac_1_dm6", "IC_8_10_K27ac_2_dm6", "VC_4_6_K27ac_1_dm6", "VC_4_6_K27ac_2_dm6", "VC_68_K27ac_1", "VC_68_K27ac_2", "VC_810_K27ac_1", "VC_810_K27ac_2", "IC_4_6_K79me3_1_dm6", "IC_4_6_K79me3_2_dm6", "IC_6_8_K79me3_1_dm6", "IC_6_8_K79me3_2_dm6", "IC_8_10_K79me3_1_dm6", "IC_8_10_K79me3_2_dm6", "VC_4_6_K79me3_1_dm6", "VC_4_6_K79me3_2_dm6", "VC_68_K79me3_1", "VC_68_K79me3_2", "VC_810_K79me3", "VC_810_K79me3_2", "IC_4_6_K4mono_1_dm6", "IC_4_6_K4mono_2_dm6", "IC_6_8_K4mono_1_dm6", "IC_6_8_K4mono_2_dm6", "IC_8_10_K4mono_1_dm6", "IC_8_10_K4mono_2_dm6", "VC_4_6_K4mono_1_dm6", "VC_4_6_K4mono_2_dm6", "VC_68_K4mono_1", "VC_68_K4mono_2", "VC_810_K4mono_1", "VC_810_K4mono_2", "IC_4_6_K27me3_1_dm6", "IC_4_6_K27me3_2_dm6", "IC_6_8_K27me3_2_dm6", "IC_6_8_K27me3_3_dm6", "IC_8_10_K27me3_1_dm6", "IC_8_10_K27me3_2_dm6", "VC_4_6_K27me3_1_dm6", "VC_4_6_K27me3_2_dm6", "VC_68_K27me3_1", "VC_68_K27me3_2", "VC_810_K27me3_1", "VC_810_K27me3_2")



filtered_res <- as.data.frame(res)

input_and_res <- cbind(RNA_ChIP_data_filter,as.data.frame(res))
input_and_res$idx_filter <- NULL


write.table(input_and_res,"DESeq2_results_RNAseq_Alex_46h_VC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

write.table(as.data.frame(mcols(dds,use.names=TRUE)),"DESeq2_additional_results_RNAseq_Alex_46h_VC_vs_NEG.txt",sep="\t",quote=F, row.names=F)
write.table(counts(dds, normalized=TRUE),"sizeNorm_counts_DESeq2_results_RNAseq_Alex_46h_VC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

#png(filename="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot.png",width=900,height=600)
par(mar=c(5,5,2,2),cex=1.5,cex.axis=1.3,cex.lab=1.5)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)
dev.off()

#pdf(file="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot_pdf.pdf",width=9,height=6)
par(mar=c(5,5,2,2),cex=1.3,cex.axis=1.1,cex.lab=1.3)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)
dev.off()

VC46 <- as.data.frame(cbind(input_and_res$FBtr, input_and_res$log2FoldChange, input_and_res$padj))
colnames(VC46) <- c("FBtr","log2FC_VC46vsNEG","padj_VC46vsNEG")



```
```{r DeSEQ68hICvsNEG}
options(scipen=999)
#DESEQ
#Prepare and choose datasets
countData <- RNA_NumReads[,c(13,14,11,12)]
colnames(countData) <- c("IC_1","IC_2","VC_1","VC_2")

colData <- as.matrix(c("IC","IC","VC","VC"),ncol=1)
rownames(colData) <- colnames(countData)
colnames(colData) <- c("sort")

dds <- DESeqDataSetFromMatrix(countData=countData,colData=colData,design = ~ sort)

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

#Filter low count bins
idx_filter <- rowSums( counts(dds, normalized=TRUE) >= 10 ) >= 2
dds <- dds[idx_filter,]

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

RNA_ChIP_data_filter <- cbind(RNA_NumReads,idx_filter)
RNA_ChIP_data_filter <- RNA_ChIP_data_filter[idx_filter,]

#DESEQ2 COMMAND

colData(dds)$sort <- factor(colData(dds)$sort,levels=c("IC","VC"))
dds <- DESeq(dds)

#Results
res <- results(dds)

#Histogram of p-values
hist(res$pvalue, col = "royalblue4", 
      xlab = "p-values",breaks=20)

cat('\r\n\r\n')
#P-value correction with BH method

res <- res[, -which(names(res) == "padj")]

FDR.DESeq2Res <- fdrtool(res$stat, statistic= "normal", plot = T)

cat('\r\n\r\n')

FDR.DESeq2Res$param[1, "sd"]

cat('\r\n\r\n')

res[,"padj"]  <- p.adjust(FDR.DESeq2Res$pval, method = "fdr")

hist(res$padj, col = "royalblue4", 
      xlab = "CORRECTED p-values",breaks=20)

cat('\r\n\r\n')

#colnames(data) <- c("chr","start","end","name","score","strand","IC_4_6_K4me3_1_dm6", "IC_4_6_K4me3_2_dm6", "IC_6_8_K4me3_1_dm6", "IC_6_8_K4me3_2_dm6", "IC_8_10_K4me3_1_dm6", "IC_8_10_K4me3_2_dm6","VC_4_6_K4me3_1_dm6","VC_4_6_K4me3_2_dm6", "VC_68_K4me3_1", "VC_68_K4me3_2", "VC_810_K4me3_1", "VC_810_K4me3_2", "IC_4_6_K27ac_1_dm6", "IC_4_6_K27ac_3", "IC_6_8_K27ac_1_dm6","IC_6_8_K27ac_3_dm6", "IC_8_10_K27ac_1_dm6", "IC_8_10_K27ac_2_dm6", "VC_4_6_K27ac_1_dm6", "VC_4_6_K27ac_2_dm6", "VC_68_K27ac_1", "VC_68_K27ac_2", "VC_810_K27ac_1", "VC_810_K27ac_2", "IC_4_6_K79me3_1_dm6", "IC_4_6_K79me3_2_dm6", "IC_6_8_K79me3_1_dm6", "IC_6_8_K79me3_2_dm6", "IC_8_10_K79me3_1_dm6", "IC_8_10_K79me3_2_dm6", "VC_4_6_K79me3_1_dm6", "VC_4_6_K79me3_2_dm6", "VC_68_K79me3_1", "VC_68_K79me3_2", "VC_810_K79me3", "VC_810_K79me3_2", "IC_4_6_K4mono_1_dm6", "IC_4_6_K4mono_2_dm6", "IC_6_8_K4mono_1_dm6", "IC_6_8_K4mono_2_dm6", "IC_8_10_K4mono_1_dm6", "IC_8_10_K4mono_2_dm6", "VC_4_6_K4mono_1_dm6", "VC_4_6_K4mono_2_dm6", "VC_68_K4mono_1", "VC_68_K4mono_2", "VC_810_K4mono_1", "VC_810_K4mono_2", "IC_4_6_K27me3_1_dm6", "IC_4_6_K27me3_2_dm6", "IC_6_8_K27me3_2_dm6", "IC_6_8_K27me3_3_dm6", "IC_8_10_K27me3_1_dm6", "IC_8_10_K27me3_2_dm6", "VC_4_6_K27me3_1_dm6", "VC_4_6_K27me3_2_dm6", "VC_68_K27me3_1", "VC_68_K27me3_2", "VC_810_K27me3_1", "VC_810_K27me3_2")



filtered_res <- as.data.frame(res)

input_and_res <- cbind(RNA_ChIP_data_filter,as.data.frame(res))
input_and_res$idx_filter <- NULL


write.table(input_and_res,"DESeq2_results_RNAseq_Alex_68h_IC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

write.table(as.data.frame(mcols(dds,use.names=TRUE)),"DESeq2_additional_results_RNAseq_Alex_68h_IC_vs_NEG.txt",sep="\t",quote=F, row.names=F)
write.table(counts(dds, normalized=TRUE),"sizeNorm_counts_DESeq2_results_RNAseq_Alex_68h_IC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

#png(filename="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot.png",width=900,height=600)
par(mar=c(5,5,2,2),cex=1.5,cex.axis=1.3,cex.lab=1.5)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)

IC68 <- as.data.frame(cbind(input_and_res$FBtr, input_and_res$log2FoldChange, input_and_res$padj))
colnames(IC68) <- c("FBtr","log2FC_IC68vsNEG","padj_IC68vsNEG")



```

```{r DeSEQ68hVCvsNEG}
options(scipen=999)
#DESEQ
#Prepare and choose datasets
countData <- RNA_NumReads[,c(17,18,15,16)]
colnames(countData) <- c("IC_1","IC_2","VC_1","VC_2")

colData <- as.matrix(c("IC","IC","VC","VC"),ncol=1)
rownames(colData) <- colnames(countData)
colnames(colData) <- c("sort")

dds <- DESeqDataSetFromMatrix(countData=countData,colData=colData,design = ~ sort)

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

#Filter low count bins
idx_filter <- rowSums( counts(dds, normalized=TRUE) >= 10 ) >= 2
dds <- dds[idx_filter,]

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

RNA_ChIP_data_filter <- cbind(RNA_NumReads,idx_filter)
RNA_ChIP_data_filter <- RNA_ChIP_data_filter[idx_filter,]

#DESEQ2 COMMAND

colData(dds)$sort <- factor(colData(dds)$sort,levels=c("IC","VC"))
dds <- DESeq(dds)

#Results
res <- results(dds)

#Histogram of p-values
hist(res$pvalue, col = "royalblue4", 
      xlab = "p-values",breaks=20)

cat('\r\n\r\n')
#P-value correction with BH method

res <- res[, -which(names(res) == "padj")]

FDR.DESeq2Res <- fdrtool(res$stat, statistic= "normal", plot = T)

cat('\r\n\r\n')

FDR.DESeq2Res$param[1, "sd"]

cat('\r\n\r\n')

res[,"padj"]  <- p.adjust(FDR.DESeq2Res$pval, method = "fdr")

hist(res$padj, col = "royalblue4", 
      xlab = "CORRECTED p-values",breaks=20)

cat('\r\n\r\n')

#colnames(data) <- c("chr","start","end","name","score","strand","IC_4_6_K4me3_1_dm6", "IC_4_6_K4me3_2_dm6", "IC_6_8_K4me3_1_dm6", "IC_6_8_K4me3_2_dm6", "IC_8_10_K4me3_1_dm6", "IC_8_10_K4me3_2_dm6","VC_4_6_K4me3_1_dm6","VC_4_6_K4me3_2_dm6", "VC_68_K4me3_1", "VC_68_K4me3_2", "VC_810_K4me3_1", "VC_810_K4me3_2", "IC_4_6_K27ac_1_dm6", "IC_4_6_K27ac_3", "IC_6_8_K27ac_1_dm6","IC_6_8_K27ac_3_dm6", "IC_8_10_K27ac_1_dm6", "IC_8_10_K27ac_2_dm6", "VC_4_6_K27ac_1_dm6", "VC_4_6_K27ac_2_dm6", "VC_68_K27ac_1", "VC_68_K27ac_2", "VC_810_K27ac_1", "VC_810_K27ac_2", "IC_4_6_K79me3_1_dm6", "IC_4_6_K79me3_2_dm6", "IC_6_8_K79me3_1_dm6", "IC_6_8_K79me3_2_dm6", "IC_8_10_K79me3_1_dm6", "IC_8_10_K79me3_2_dm6", "VC_4_6_K79me3_1_dm6", "VC_4_6_K79me3_2_dm6", "VC_68_K79me3_1", "VC_68_K79me3_2", "VC_810_K79me3", "VC_810_K79me3_2", "IC_4_6_K4mono_1_dm6", "IC_4_6_K4mono_2_dm6", "IC_6_8_K4mono_1_dm6", "IC_6_8_K4mono_2_dm6", "IC_8_10_K4mono_1_dm6", "IC_8_10_K4mono_2_dm6", "VC_4_6_K4mono_1_dm6", "VC_4_6_K4mono_2_dm6", "VC_68_K4mono_1", "VC_68_K4mono_2", "VC_810_K4mono_1", "VC_810_K4mono_2", "IC_4_6_K27me3_1_dm6", "IC_4_6_K27me3_2_dm6", "IC_6_8_K27me3_2_dm6", "IC_6_8_K27me3_3_dm6", "IC_8_10_K27me3_1_dm6", "IC_8_10_K27me3_2_dm6", "VC_4_6_K27me3_1_dm6", "VC_4_6_K27me3_2_dm6", "VC_68_K27me3_1", "VC_68_K27me3_2", "VC_810_K27me3_1", "VC_810_K27me3_2")



filtered_res <- as.data.frame(res)

input_and_res <- cbind(RNA_ChIP_data_filter,as.data.frame(res))
input_and_res$idx_filter <- NULL


write.table(input_and_res,"DESeq2_results_RNAseq_Alex_68h_VC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

write.table(as.data.frame(mcols(dds,use.names=TRUE)),"DESeq2_additional_results_RNAseq_Alex_68h_VC_vs_NEG.txt",sep="\t",quote=F, row.names=F)
write.table(counts(dds, normalized=TRUE),"sizeNorm_counts_DESeq2_results_RNAseq_Alex_68h_VC_vs_NEG.txt",sep="\t",quote=F, row.names=F)

#png(filename="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot.png",width=900,height=600)
par(mar=c(5,5,2,2),cex=1.5,cex.axis=1.3,cex.lab=1.5)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)

VC68 <- as.data.frame(cbind(input_and_res$FBtr, input_and_res$log2FoldChange, input_and_res$padj))
colnames(VC68) <- c("FBtr","log2FC_VC68vsNEG","padj_VC68vsNEG")



```

```{r DeSEQ46hICvsVC}
options(scipen=999)
#DESEQ
#Prepare and choose datasets
countData <- RNA_NumReads[,c(5,6,9,10)]
colnames(countData) <- c("IC_1","IC_2","VC_1","VC_2")

colData <- as.matrix(c("IC","IC","VC","VC"),ncol=1)
rownames(colData) <- colnames(countData)
colnames(colData) <- c("sort")

dds <- DESeqDataSetFromMatrix(countData=countData,colData=colData,design = ~ sort)

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

#Filter low count bins
idx_filter <- rowSums( counts(dds, normalized=TRUE) >= 10 ) >= 2
dds <- dds[idx_filter,]

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

RNA_ChIP_data_filter <- cbind(RNA_NumReads,idx_filter)
RNA_ChIP_data_filter <- RNA_ChIP_data_filter[idx_filter,]

#DESEQ2 COMMAND

colData(dds)$sort <- factor(colData(dds)$sort,levels=c("IC","VC"))
dds <- DESeq(dds)

#Results
res <- results(dds)

#Histogram of p-values
hist(res$pvalue, col = "royalblue4", 
      xlab = "p-values",breaks=20)

cat('\r\n\r\n')
#P-value correction with BH method

res <- res[, -which(names(res) == "padj")]

FDR.DESeq2Res <- fdrtool(res$stat, statistic= "normal", plot = T)

cat('\r\n\r\n')

FDR.DESeq2Res$param[1, "sd"]

cat('\r\n\r\n')

res[,"padj"]  <- p.adjust(FDR.DESeq2Res$pval, method = "fdr")

hist(res$padj, col = "royalblue4", 
      xlab = "CORRECTED p-values",breaks=20)

cat('\r\n\r\n')

#colnames(data) <- c("chr","start","end","name","score","strand","IC_4_6_K4me3_1_dm6", "IC_4_6_K4me3_2_dm6", "IC_6_8_K4me3_1_dm6", "IC_6_8_K4me3_2_dm6", "IC_8_10_K4me3_1_dm6", "IC_8_10_K4me3_2_dm6","VC_4_6_K4me3_1_dm6","VC_4_6_K4me3_2_dm6", "VC_68_K4me3_1", "VC_68_K4me3_2", "VC_810_K4me3_1", "VC_810_K4me3_2", "IC_4_6_K27ac_1_dm6", "IC_4_6_K27ac_3", "IC_6_8_K27ac_1_dm6","IC_6_8_K27ac_3_dm6", "IC_8_10_K27ac_1_dm6", "IC_8_10_K27ac_2_dm6", "VC_4_6_K27ac_1_dm6", "VC_4_6_K27ac_2_dm6", "VC_68_K27ac_1", "VC_68_K27ac_2", "VC_810_K27ac_1", "VC_810_K27ac_2", "IC_4_6_K79me3_1_dm6", "IC_4_6_K79me3_2_dm6", "IC_6_8_K79me3_1_dm6", "IC_6_8_K79me3_2_dm6", "IC_8_10_K79me3_1_dm6", "IC_8_10_K79me3_2_dm6", "VC_4_6_K79me3_1_dm6", "VC_4_6_K79me3_2_dm6", "VC_68_K79me3_1", "VC_68_K79me3_2", "VC_810_K79me3", "VC_810_K79me3_2", "IC_4_6_K4mono_1_dm6", "IC_4_6_K4mono_2_dm6", "IC_6_8_K4mono_1_dm6", "IC_6_8_K4mono_2_dm6", "IC_8_10_K4mono_1_dm6", "IC_8_10_K4mono_2_dm6", "VC_4_6_K4mono_1_dm6", "VC_4_6_K4mono_2_dm6", "VC_68_K4mono_1", "VC_68_K4mono_2", "VC_810_K4mono_1", "VC_810_K4mono_2", "IC_4_6_K27me3_1_dm6", "IC_4_6_K27me3_2_dm6", "IC_6_8_K27me3_2_dm6", "IC_6_8_K27me3_3_dm6", "IC_8_10_K27me3_1_dm6", "IC_8_10_K27me3_2_dm6", "VC_4_6_K27me3_1_dm6", "VC_4_6_K27me3_2_dm6", "VC_68_K27me3_1", "VC_68_K27me3_2", "VC_810_K27me3_1", "VC_810_K27me3_2")



filtered_res <- as.data.frame(res)

input_and_res <- cbind(RNA_ChIP_data_filter,as.data.frame(res))
input_and_res$idx_filter <- NULL


write.table(input_and_res,"DESeq2_results_RNAseq_Alex_46h_IC_vs_VC.txt",sep="\t",quote=F, row.names=F)

write.table(as.data.frame(mcols(dds,use.names=TRUE)),"DESeq2_additional_results_RNAseq_Alex_46h_IC_vs_VC.txt",sep="\t",quote=F, row.names=F)
write.table(counts(dds, normalized=TRUE),"sizeNorm_counts_DESeq2_results_RNAseq_Alex_46h_IC_vs_VC.txt",sep="\t",quote=F, row.names=F)

#png(filename="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot.png",width=900,height=600)
par(mar=c(5,5,2,2),cex=1.5,cex.axis=1.3,cex.lab=1.5)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)


ICvsVC46 <- as.data.frame(cbind(input_and_res$FBtr, input_and_res$log2FoldChange, input_and_res$padj))
colnames(ICvsVC46) <- c("FBtr","log2FC_ICvsVC46","padj_ICvsVC46")


```

```{r DeSEQ46hICvsVC}
options(scipen=999)
#DESEQ
#Prepare and choose datasets
countData <- RNA_NumReads[,c(13,14,17,18)]
colnames(countData) <- c("IC_1","IC_2","VC_1","VC_2")

colData <- as.matrix(c("IC","IC","VC","VC"),ncol=1)
rownames(colData) <- colnames(countData)
colnames(colData) <- c("sort")

dds <- DESeqDataSetFromMatrix(countData=countData,colData=colData,design = ~ sort)

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

#Filter low count bins
idx_filter <- rowSums( counts(dds, normalized=TRUE) >= 10 ) >= 2
dds <- dds[idx_filter,]

dds <- estimateSizeFactors(dds)
sizeFactors(dds)

RNA_ChIP_data_filter <- cbind(RNA_NumReads,idx_filter)
RNA_ChIP_data_filter <- RNA_ChIP_data_filter[idx_filter,]

#DESEQ2 COMMAND

colData(dds)$sort <- factor(colData(dds)$sort,levels=c("IC","VC"))
dds <- DESeq(dds)

#Results
res <- results(dds)

#Histogram of p-values
hist(res$pvalue, col = "royalblue4", 
      xlab = "p-values",breaks=20)

cat('\r\n\r\n')
#P-value correction with BH method

res <- res[, -which(names(res) == "padj")]

FDR.DESeq2Res <- fdrtool(res$stat, statistic= "normal", plot = T)

cat('\r\n\r\n')

FDR.DESeq2Res$param[1, "sd"]

cat('\r\n\r\n')

res[,"padj"]  <- p.adjust(FDR.DESeq2Res$pval, method = "fdr")

hist(res$padj, col = "royalblue4", 
      xlab = "CORRECTED p-values",breaks=20)

cat('\r\n\r\n')

#colnames(data) <- c("chr","start","end","name","score","strand","IC_4_6_K4me3_1_dm6", "IC_4_6_K4me3_2_dm6", "IC_6_8_K4me3_1_dm6", "IC_6_8_K4me3_2_dm6", "IC_8_10_K4me3_1_dm6", "IC_8_10_K4me3_2_dm6","VC_4_6_K4me3_1_dm6","VC_4_6_K4me3_2_dm6", "VC_68_K4me3_1", "VC_68_K4me3_2", "VC_810_K4me3_1", "VC_810_K4me3_2", "IC_4_6_K27ac_1_dm6", "IC_4_6_K27ac_3", "IC_6_8_K27ac_1_dm6","IC_6_8_K27ac_3_dm6", "IC_8_10_K27ac_1_dm6", "IC_8_10_K27ac_2_dm6", "VC_4_6_K27ac_1_dm6", "VC_4_6_K27ac_2_dm6", "VC_68_K27ac_1", "VC_68_K27ac_2", "VC_810_K27ac_1", "VC_810_K27ac_2", "IC_4_6_K79me3_1_dm6", "IC_4_6_K79me3_2_dm6", "IC_6_8_K79me3_1_dm6", "IC_6_8_K79me3_2_dm6", "IC_8_10_K79me3_1_dm6", "IC_8_10_K79me3_2_dm6", "VC_4_6_K79me3_1_dm6", "VC_4_6_K79me3_2_dm6", "VC_68_K79me3_1", "VC_68_K79me3_2", "VC_810_K79me3", "VC_810_K79me3_2", "IC_4_6_K4mono_1_dm6", "IC_4_6_K4mono_2_dm6", "IC_6_8_K4mono_1_dm6", "IC_6_8_K4mono_2_dm6", "IC_8_10_K4mono_1_dm6", "IC_8_10_K4mono_2_dm6", "VC_4_6_K4mono_1_dm6", "VC_4_6_K4mono_2_dm6", "VC_68_K4mono_1", "VC_68_K4mono_2", "VC_810_K4mono_1", "VC_810_K4mono_2", "IC_4_6_K27me3_1_dm6", "IC_4_6_K27me3_2_dm6", "IC_6_8_K27me3_2_dm6", "IC_6_8_K27me3_3_dm6", "IC_8_10_K27me3_1_dm6", "IC_8_10_K27me3_2_dm6", "VC_4_6_K27me3_1_dm6", "VC_4_6_K27me3_2_dm6", "VC_68_K27me3_1", "VC_68_K27me3_2", "VC_810_K27me3_1", "VC_810_K27me3_2")



filtered_res <- as.data.frame(res)

input_and_res <- cbind(RNA_ChIP_data_filter,as.data.frame(res))
input_and_res$idx_filter <- NULL


write.table(input_and_res,"DESeq2_results_RNAseq_Alex_68h_IC_vs_VC.txt",sep="\t",quote=F, row.names=F)

write.table(as.data.frame(mcols(dds,use.names=TRUE)),"DESeq2_additional_results_RNAseq_Alex_68h_IC_vs_VC.txt",sep="\t",quote=F, row.names=F)
write.table(counts(dds, normalized=TRUE),"sizeNorm_counts_DESeq2_results_RNAseq_Alex_68h_IC_vs_VC.txt",sep="\t",quote=F, row.names=F)

#png(filename="tissue_VCvsIC_K27me3_810_BabyTADs_deseq2_ma_plot.png",width=900,height=600)
par(mar=c(5,5,2,2),cex=1.5,cex.axis=1.3,cex.lab=1.5)
plotMA(dds,ylim=c(-15,15),main="",alpha=0.05)

ICvsVC68 <- as.data.frame(cbind(input_and_res$FBtr, input_and_res$log2FoldChange, input_and_res$padj))
colnames(ICvsVC68) <-  c("FBtr","log2FC_ICvsVC68","padj_ICvsVC68")


```



```{r combine}


  
  TRIERBNF <- merge(input_and_res[,1:18],IC46, by= c("FBtr"), all.x =T)
TRIERBNF <- merge(TRIERBNF,IC68, by= c("FBtr"), all.x =T)
TRIERBNF <- merge(TRIERBNF,VC46, by= c("FBtr"), all.x =T)
TRIERBNF <- merge(TRIERBNF,VC68, by= c("FBtr"), all.x =T)
TRIERBNF <- unique(TRIERBNF) 
TRIERBNF <- merge(TRIERBNF,ICvsVC46, by= c("FBtr"), all.x =T)
TRIERBNF <- merge(TRIERBNF,ICvsVC68, by= c("FBtr"), all.x =T)
TRIERBNF <- merge(TRIERBNF,ID_FBtr_table, by= c("FBtr"), all.x =T)

Combined_large_RNA_list <- unique(TRIERBNF) 
  
write.table(Combined_large_RNA_list, file="Differential_RNA_seq_analysis_combined_DeSEq_list_FBgn.txt",sep="\t",quote=F, row.names=F)

#Tescht <- as.data.frame(Combined_large_RNA_list[,1])
#write.csv(Tescht, file="all_FBtr.txt",sep="\t",quote=F, row.names=F)

Combined_large_RNA_list_2 <-  read.table("C:/Users/Admin/Documents/RNA_Seq_OWN_DESeq/Differential_RNA_seq_analysis_combined_DeSEq_list_FBgn.txt",stringsAsFactors=F, sep= "\t",header=TRUE) 


````
